### ISSUE TITLE
Add proxy support

### ISSUE THREAD

**Issue by tjarrettveracode** [veracode/veracode-api-py#30]
Customer reports:

> I need to use proxy to connect to Veracode servers and Veracode Pipeline Mitigation does not allow for that. It uses Python requests module under the hood which allows to use http_proxy and https_proxy env variables. However, proxies are explicitly defined in:
 
> https://github.com/tjarrettveracode/veracode-api-py/blob/master/veracode_api_py/apihelper.py
 
> `session.send(prepared_request, proxies=self.proxies)` 

> and because of that fact env variables are not taken into account.

**Comment by alexpoloniewicz** [comment]
@tjarrettveracode I am also in the same boat. Are there any hotfixes I can do currently to allow python to utilize the env variables?
