### ISSUE TITLE
SCA: Add arguments for selecting branches

### ISSUE THREAD

**Issue by Gby56** [veracode/veracode-api-py#35]
I'd like to be able to specify a branch in `get_project_issues()`, currently it calls `APIHelper()._rest_paged_request(uri,"GET","issues",{})` with an empty `{}` for params

https://github.com/veracode/veracode-api-py/blob/a87b1d64327465e4abcae73a438c49d4ea290fe2/veracode_api_py/sca.py#L49

**Comment by tjarrettveracode** [comment]
Thanks for filing this! I'm reviewing the pull request and will merge once I've gotten through it.
