### ISSUE TITLE
Get teams per workspace

### ISSUE THREAD

**Issue by Gby56** [veracode/veracode-api-py#41]
I think it's missing for now, https://app.swaggerhub.com/apis/Veracode/veracode-sca_agent_api_specification/3.0#/workspaces/getTeamsUsingGET_1

**Comment by tjarrettveracode** [comment]
Good catch, added a get_teams method on the Workspaces() object that can also be called from the VeracodeAPI() object as get_workspace_teams().

**Comment by tjarrettveracode** [comment]
Release pending, stay tuned.

**Comment by Gby56** [comment]
haha crap, I implemented my own python requests function meanwhile :P

**Comment by Gby56** [comment]
by the way, I'm "kinda" writing a "veracode user, sast apps, sca workspace management" as code... like a terraform provider
That would be nice to contribute back, not sure if you had plans to make an official terraform ?

**Comment by tjarrettveracode** [comment]
Very cool. I don't think there's anything official in the works but would love to see what you have cooking.

**Comment by Gby56** [comment]
I'm simply dumping a few apis and building an overall JSON, that is projected by team for each key.
Then, each team object has the sast applications, the sca workspaces, and users
So if I manage to get this working, i should be able to manage things pretty damn well
