### ISSUE TITLE
SBOM generation doesn't support linked=true

### ISSUE THREAD

**Issue by gmdavef** [veracode/veracode-api-py#51]
For an application, the SBOM API endpoint allows for parameter "linked=true". This causes the generated SBOM to include components from any linked projects. However, the default value is false and there's no way to set the parameter. Therefore it's not possible for data from a linked project to show up in the generated SBOM for an application.

**Comment by tjarrettveracode** [comment]
@gmdavef -- the latest release (v 0.9.35) on pypi now contains the changes to support this request.
