### ISSUE TITLE
Getting xml back from veracode_api.get_app_list()

### ISSUE THREAD

**Issue by keeely** [veracode/veracode-api-py#67]
I ran the following code (with value API token in the right place)

```
from veracode_api_py import VeracodeAPI
veracode_api = VeracodeAPI()
print(veracode_api.get_app_list())
```

It works but gives me XML.  I was expecting a Python wrapper to give back a list.  I'm not having a go at anyone, just want to understand if I'm driving this wrong before I start writing code to parse my responses.

**Comment by tjarrettveracode** [comment]
Hi @keeely , thanks for the feedback. The library was designed as a wrapper around Veracode APIs but it does not abstract the output of API commands, so if you call one of the legacy methods you'll get XML. The modern methods will all return a proper dictionary or list as appropriate. 

There is a modern equivalent for the `get_app_list` call that returns a list. Try `get_apps` instead; see the [docs](https://github.com/veracode/veracode-api-py/blob/main/docs/applications.md) for details.
